import {
  backfillAttributionAction,
  createDomain,
  deleteAdminUserRecord,
  deleteDomain,
  fetchAdminOverview,
  fetchAdminSites,
  fetchAdminUsers,
  fetchApiKeys,
  exportRawAction,
  fetchConsent,
  fetchDomains,
  fetchDestinationDetail,
  fetchDeliveries,
  fetchDestinations,
  fetchDlq,
  fetchEvent,
  fetchEvents,
  fetchHealth,
  fetchInstall,
  fetchJobs,
  fetchJourneys,
  fetchOverview,
  fetchQueues,
  fetchRealtime,
  fetchRouteDetail,
  fetchRoutes,
  fetchSchemas,
  fetchTransformationDetail,
  fetchTransformations,
  fetchUsers,
  flushForwarderAction,
  replayDlqAction,
  replayEventAction,
  updateAdminUserPassword,
  updateAdminUserRecord
} from "./api-client";

export const currentContext = {
  orgId: "org_open",
  orgName: "Open Commerce Lab",
  projectId: "project_gateway",
  projectName: "Events Core",
  siteId: "site_alpha",
  siteName: "goldring.ro",
  environment: "production",
  dateRange: "24h"
} as const;

export const qk = {
  overview: (siteId: string, range: string) => ["sites", siteId, "overview", range],
  realtime: (siteId: string) => ["sites", siteId, "realtime"],
  events: (siteId: string) => ["sites", siteId, "events", "recent"],
  schemas: (siteId: string) => ["sites", siteId, "events", "schemas"],
  routes: (siteId: string) => ["sites", siteId, "routes"],
  destinations: (siteId: string) => ["sites", siteId, "destinations"],
  transformations: (siteId: string) => ["sites", siteId, "transformations"],
  deliveries: (siteId: string) => ["sites", siteId, "deliveries"],
  event: (siteId: string, eventId: string) => ["sites", siteId, "events", eventId],
  health: (siteId: string) => ["sites", siteId, "operations", "health"],
  queues: (siteId: string) => ["sites", siteId, "operations", "queues"],
  dlq: (siteId: string) => ["sites", siteId, "operations", "dlq"],
  jobs: (siteId: string) => ["sites", siteId, "operations", "jobs"],
  users: (siteId: string) => ["sites", siteId, "identity", "users"],
  journeys: (siteId: string, canonicalUserId: string) => ["sites", siteId, "identity", "journeys", canonicalUserId],
  consent: (siteId: string) => ["sites", siteId, "identity", "consent"],
  install: (siteId: string) => ["sites", siteId, "settings", "install"],
  domains: (siteId: string) => ["sites", siteId, "settings", "domains"],
  apiKeys: (siteId: string) => ["sites", siteId, "settings", "api-keys"],
  adminOverview: () => ["admin", "overview"],
  adminUsers: () => ["admin", "users"],
  adminSites: () => ["admin", "sites"],
  route: (siteId: string, routeId: string) => ["sites", siteId, "routes", routeId],
  transformation: (siteId: string, transformationId: string) => ["sites", siteId, "transformations", transformationId],
  destination: (siteId: string, destinationId: string) => ["sites", siteId, "destinations", destinationId]
} as const;

export const dashboardApi = {
  fetchOverview: () => fetchOverview(currentContext.siteId, currentContext.dateRange),
  fetchRealtime: () => fetchRealtime(currentContext.siteId),
  fetchEvents: () => fetchEvents(currentContext.siteId),
  fetchSchemas: () => fetchSchemas(currentContext.siteId),
  fetchRoutes: () => fetchRoutes(currentContext.siteId),
  fetchRouteDetail: (routeId: string) => fetchRouteDetail(currentContext.siteId, routeId),
  fetchDeliveries: () => fetchDeliveries(currentContext.siteId),
  fetchEvent: (eventId: string) => fetchEvent(currentContext.siteId, eventId),
  fetchHealth: () => fetchHealth(currentContext.siteId),
  fetchDestinations: () => fetchDestinations(currentContext.siteId),
  fetchDestinationDetail: (destinationId: string) => fetchDestinationDetail(currentContext.siteId, destinationId),
  fetchTransformations: () => fetchTransformations(currentContext.siteId),
  fetchTransformationDetail: (transformationId: string) => fetchTransformationDetail(currentContext.siteId, transformationId),
  fetchUsers: () => fetchUsers(currentContext.siteId),
  fetchJourneys: (canonicalUserId: string) => fetchJourneys(currentContext.siteId, canonicalUserId),
  fetchConsent: () => fetchConsent(currentContext.siteId),
  fetchInstall: () => fetchInstall(currentContext.siteId),
  fetchDomains: () => fetchDomains(currentContext.siteId),
  createDomain: (input: { domain: string; kind?: string; description?: string }) => createDomain(currentContext.siteId, input),
  deleteDomain: (domainId: string) => deleteDomain(currentContext.siteId, domainId),
  fetchApiKeys: () => fetchApiKeys(currentContext.siteId),
  fetchAdminOverview: () => fetchAdminOverview(),
  fetchAdminUsers: () => fetchAdminUsers(),
  updateAdminUser: (userId: string, input: { role?: "member" | "global_admin"; status?: "active" | "blocked" }) =>
    updateAdminUserRecord(userId, input),
  updateAdminUserPassword: (userId: string, password: string) => updateAdminUserPassword(userId, password),
  deleteAdminUser: (userId: string) => deleteAdminUserRecord(userId),
  fetchAdminSites: () => fetchAdminSites(),
  fetchQueues: () => fetchQueues(currentContext.siteId),
  fetchDlq: () => fetchDlq(currentContext.siteId),
  fetchJobs: () => fetchJobs(currentContext.siteId),
  replayDlq: () => replayDlqAction(currentContext.siteId),
  replayEvent: (eventId: string) => replayEventAction(currentContext.siteId, eventId),
  flushForwarder: () => flushForwarderAction(currentContext.siteId),
  backfillAttribution: () => backfillAttributionAction(currentContext.siteId),
  exportRaw: () => exportRawAction(currentContext.siteId)
};
